"""initial_schema

Revision ID: 8c9506615e64
Revises: 
Create Date: 2026-02-25 22:45:31.417823+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c9506615e64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_audit_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ro_id', sa.String(length=20), nullable=True),
    sa.Column('agent_name', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('loyalty_tier', sa.Integer(), nullable=True),
    sa.Column('loyalty_tier_name', sa.String(length=20), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('total_visits', sa.Integer(), nullable=True),
    sa.Column('payment_behavior', sa.String(length=20), nullable=True),
    sa.Column('avg_payment_days', sa.Integer(), nullable=True),
    sa.Column('preferred_contact', sa.String(length=20), nullable=True),
    sa.Column('vehicle_vins', sa.JSON(), nullable=True),
    sa.Column('is_corporate', sa.Boolean(), nullable=True),
    sa.Column('marketing_consent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('inventory',
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('oem_part_number', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('unit_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('sell_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('compatible_makes', sa.JSON(), nullable=True),
    sa.Column('compatible_models', sa.JSON(), nullable=True),
    sa.Column('compatible_years', sa.JSON(), nullable=True),
    sa.Column('compatible_fuel_types', sa.JSON(), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('bin_location', sa.String(length=20), nullable=True),
    sa.Column('qty_on_hand', sa.Integer(), nullable=True),
    sa.Column('qty_reserved', sa.Integer(), nullable=True),
    sa.Column('reorder_point', sa.Integer(), nullable=True),
    sa.Column('reorder_quantity', sa.Integer(), nullable=True),
    sa.Column('stock_status', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('part_number')
    )
    op.create_table('labor_operations',
    sa.Column('operation_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('flat_rate_hours', sa.Float(), nullable=True),
    sa.Column('skill_level', sa.String(length=30), nullable=True),
    sa.Column('related_parts_categories', sa.JSON(), nullable=True),
    sa.Column('rate_per_hour', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('operation_code')
    )
    op.create_table('purchase_orders',
    sa.Column('po_id', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.String(length=20), nullable=True),
    sa.Column('total_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('on_time', sa.Boolean(), nullable=True),
    sa.Column('days_late', sa.Integer(), nullable=True),
    sa.Column('fill_rate', sa.Float(), nullable=True),
    sa.Column('partial_delivery', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('raised_by', sa.String(length=50), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('po_id')
    )
    op.create_table('quotes',
    sa.Column('quote_id', sa.String(length=20), nullable=False),
    sa.Column('ro_id', sa.String(length=20), nullable=False),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('gst_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('oem_quote', sa.JSON(), nullable=True),
    sa.Column('aftermarket_quote', sa.JSON(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('quote_id')
    )
    op.create_table('repair_orders',
    sa.Column('ro_id', sa.String(length=20), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('service_advisor_id', sa.String(length=20), nullable=True),
    sa.Column('service_advisor_name', sa.String(length=100), nullable=True),
    sa.Column('technician_id', sa.String(length=20), nullable=True),
    sa.Column('technician_name', sa.String(length=100), nullable=True),
    sa.Column('bay', sa.String(length=20), nullable=True),
    sa.Column('fault_category', sa.String(length=50), nullable=True),
    sa.Column('complaint_text', sa.Text(), nullable=True),
    sa.Column('dtc_codes', sa.JSON(), nullable=True),
    sa.Column('vehicle_make', sa.String(length=50), nullable=True),
    sa.Column('vehicle_model', sa.String(length=50), nullable=True),
    sa.Column('vehicle_year', sa.Integer(), nullable=True),
    sa.Column('vehicle_fuel_type', sa.String(length=20), nullable=True),
    sa.Column('is_ev_job', sa.Boolean(), nullable=True),
    sa.Column('parts_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('labor_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('gst_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('final_total', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('classification_payload', sa.JSON(), nullable=True),
    sa.Column('inventory_payload', sa.JSON(), nullable=True),
    sa.Column('quote_id', sa.String(length=20), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('warranty_claim', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ro_id')
    )
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('integration_type', sa.String(length=20), nullable=True),
    sa.Column('specialization', sa.JSON(), nullable=True),
    sa.Column('categories_supplied', sa.JSON(), nullable=True),
    sa.Column('current_on_time_rate', sa.Float(), nullable=True),
    sa.Column('current_fill_rate', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('composite_score_pct', sa.Float(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('min_order_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('api_capable', sa.Boolean(), nullable=True),
    sa.Column('reliability_tier', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_table('vehicles',
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('trim', sa.String(length=50), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('engine_code', sa.String(length=30), nullable=True),
    sa.Column('transmission', sa.String(length=30), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('registration_number', sa.String(length=20), nullable=True),
    sa.Column('registration_state', sa.String(length=5), nullable=True),
    sa.Column('warranty_expired', sa.Boolean(), nullable=True),
    sa.Column('battery_capacity_kwh', sa.Float(), nullable=True),
    sa.Column('is_ev', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('vin')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('suppliers')
    op.drop_table('repair_orders')
    op.drop_table('quotes')
    op.drop_table('purchase_orders')
    op.drop_table('labor_operations')
    op.drop_table('inventory')
    op.drop_table('customers')
    op.drop_table('agent_audit_log')
    # ### end Alembic commands ###
